package com.diffblue.demo.tdd.controllers;

import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import javassist.CannotCompileException;
import javassist.NotFoundException;
import javassist.bytecode.BadBytecode;

import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.tdd.models.Product;
import com.diffblue.demo.tdd.repositories.ProductRepository;

import org.mockito.Matchers;
import org.mockito.Mockito;
import org.junit.Rule;

public class CartControllerTest {

  @Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: CartController */

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testConstructor() {

      /* Arrange */
      ProductRepository productRepo = null;

      /* Act */
      /* Creating object to test constructor */
      new CartController(productRepo);

      /* Testing that constructor does not throw an exception */
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddCartItem() {

    /* Arrange */
    ProductRepository productRepo = null;
    CartController cartController = new CartController(productRepo);
    HttpServletRequest request = null;
    HttpSession session = null;

    /* Act */
    String retval = cartController.addCartItem(request, session);

    /* Assert result */
    Assert.assertNotNull(retval);
    Assert.assertEquals("redirect:/cart", retval);
  }
  
  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddProductToCart() throws ClassNotFoundException,
  InstantiationException, IllegalAccessException, NotFoundException,
  CannotCompileException, BadBytecode {

    /* Arrange */
    ProductRepository productRepository = (ProductRepository) Reflector
      .getInstance("com.diffblue.demo.tdd.repositories.ProductRepository");
    CartController cartController = new CartController(productRepository);
    String productParam = null;
    HashMap<Integer, Integer> cartItems = null;

    /* Act */
    thrown.expect(IllegalArgumentException.class);
    cartController.addProductToCart(productParam, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddProductToCartWithProductParamEmpty() throws ClassNotFoundException,
      InstantiationException, IllegalAccessException, NotFoundException,
      CannotCompileException, BadBytecode {
    /* Arrange */
    ProductRepository productRepository = (ProductRepository) Reflector
        .getInstance("com.diffblue.demo.tdd.repositories.ProductRepository");
    CartController cartController = new CartController(productRepository);
    String productParam = "";
    HashMap<Integer, Integer> cartItems = new HashMap<>();

    /* Act */
    thrown.expect(IllegalArgumentException.class);
    cartController.addProductToCart(productParam, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddProductToCartWithProductParam0() {
    /* Setup mocks */
    Product mockProduct = new Product();
    mockProduct.setDescription("");
    mockProduct.setPrice(0.0);
    mockProduct.setId(0);
    mockProduct.setName("");
    ProductRepository productRepository =
        (ProductRepository) Mockito.mock(ProductRepository.class);
    Mockito.when(productRepository.findById(Matchers.anyInt()))
    .thenReturn(mockProduct);

    /* Arrange */
    CartController cartController = new CartController(productRepository);
    String productParam = "0";
    HashMap<Integer, Integer> cartItems = new HashMap<>();

    /* Act */
    cartController.addProductToCart(productParam, cartItems);
    
    /* Assert result */
    Assert.assertNotNull(cartItems);
    HashMap<Integer, Integer> hashMap = new HashMap<>();
    hashMap.put(0, 1);
    Assert.assertEquals(hashMap, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddProductToCartWithProductParam2() {
    /* Setup mocks */
    ProductRepository productRepository =
        (ProductRepository) Mockito.mock(ProductRepository.class);
    Mockito.when(productRepository.findById(Matchers.anyInt()))
      .thenReturn(null);

    /* Arrange */
    CartController cartController = new CartController(productRepository);
    String productParam = "+2";
    HashMap<Integer, Integer> cartItems = new HashMap<>();
    cartItems.put(null, 0);

    /* Act */
    thrown.expect(IllegalArgumentException.class);
    cartController.addProductToCart(productParam, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void testAddProductToCartTestWithCartItemsNonEmpty() {
    /* Setup mocks */
    Product mockProduct = new Product();
    mockProduct.setDescription("");
    mockProduct.setPrice(0.0);
    mockProduct.setId(0);
    mockProduct.setName("");
    ProductRepository productRepository =
        (ProductRepository) Mockito.mock(ProductRepository.class);
    Mockito.when(productRepository.findById(Matchers.anyInt()))
      .thenReturn(mockProduct);

    /* Arrange */
    CartController cartController = new CartController(productRepository);
    String productParam = "0";
    HashMap<Integer, Integer> cartItems = new HashMap<>();
    cartItems.put(0, 2);

    /* Act */
    cartController.addProductToCart(productParam, cartItems);

    /* Assert result */
    Assert.assertNotNull(cartItems);
    HashMap<Integer, Integer> hashMap = new HashMap<>();
    hashMap.put(0, 3);
    Assert.assertEquals(hashMap, cartItems);
  }
}
