package com.diffblue.demo.tdd.controllers;

import java.util.ArrayList;
import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import javassist.CannotCompileException;
import javassist.NotFoundException;
import javassist.bytecode.BadBytecode;

import org.junit.Assert;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import com.diffblue.deeptestutils.IterAnswer;
import com.diffblue.deeptestutils.Reflector;
import com.diffblue.demo.tdd.models.Product;
import com.diffblue.demo.tdd.repositories.ProductRepository;

import org.mockito.Mockito;
import org.junit.Rule;
import org.mockito.Matchers;

public class CartControllerTest {

  @Rule
  public ExpectedException thrown = ExpectedException.none();

  /* testedClasses: CartController */

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void constructor000() {

      /* Arrange */
      ProductRepository productRepo = null;

      /* Act */
      /* Creating object to test constructor */
      new CartController(productRepo);

      /* Testing that constructor does not throw an exception */
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void addCartItem000() throws Throwable {

    /* Arrange */
    ProductRepository productRepo = null;
    CartController cartController = new CartController(productRepo);
    HttpServletRequest request = null;
    HttpSession session = null;

    /* Act */
    String retval = cartController.addCartItem(request, session);

    /* Assert result */
    Assert.assertNotNull(retval);
    Assert.assertEquals("redirect:/cart", retval);
  }
  
  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void addProductToCartTest000() throws ClassNotFoundException,
  InstantiationException, IllegalAccessException, NotFoundException,
  CannotCompileException, BadBytecode {

    /* Arrange */
    ProductRepository productRepository = (ProductRepository) Reflector
      .getInstance("com.diffblue.demo.tdd.repositories.ProductRepository");
    CartController cartController = new CartController(productRepository);
    String productParam = null;
    HashMap<Integer, Integer> cartItems = null;

    /* Act */
    thrown.expect(IllegalArgumentException.class);
    cartController.addProductToCart(productParam, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void addProductToCartTest001() throws ClassNotFoundException,
      InstantiationException, IllegalAccessException, NotFoundException,
      CannotCompileException, BadBytecode {
    /* Arrange */
    ProductRepository productRepository = (ProductRepository) Reflector
        .getInstance("com.diffblue.demo.tdd.repositories.ProductRepository");
    CartController cartController = new CartController(productRepository);
    String productParam = "";
    HashMap<Integer, Integer> cartItems = new HashMap<Integer, Integer>();

    /* Act */
    thrown.expect(IllegalArgumentException.class);
    cartController.addProductToCart(productParam, cartItems);
  }

  /*
   * Test generated by Diffblue Deeptest.
   */
  @Test
  public void addProductToCartTest002() {
    
    /* Setup mocks */
    Product mockProduct1 = new Product();
    mockProduct1.setDescription("");
    mockProduct1.setPrice(0.0);
    mockProduct1.setId(0);
    mockProduct1.setName("");
    final ArrayList<Product> productRepositoryFindByIdAnswers = 
      new ArrayList<Product>();
    final ArrayList<Object[]> productRepositoryFindByIdExpectations = 
      new ArrayList<Object[]>();
    final IterAnswer<Product> productRepositoryFindByIdAnswer = 
      new IterAnswer<Product>(
        "com.diffblue.demo.tdd.repositories.ProductRepository", "findById",
        productRepositoryFindByIdAnswers, productRepositoryFindByIdExpectations);
    productRepositoryFindByIdAnswers.add(mockProduct1);
    ArrayList<ProductRepository> productRepositoryInstances = 
      new ArrayList<ProductRepository>();

    /* Arrange */
    ProductRepository productRepository = 
      (ProductRepository) Mockito.mock(ProductRepository.class);
    productRepositoryInstances.add(productRepository);
    CartController cartController = new CartController(productRepository);
    String productParam = "0";
    HashMap<Integer, Integer> cartItems = new HashMap<Integer, Integer>();
    for (ProductRepository productRepositoryIter : productRepositoryInstances) {
      Mockito.when(productRepositoryIter.findById(Matchers.anyInt()))
        .thenAnswer(productRepositoryFindByIdAnswer);
    }

    /* Act */
    cartController.addProductToCart(productParam, cartItems);
    
    /* Assert result */
    Assert.assertNotNull(cartItems);
    HashMap<Integer, Integer> hashMap = new HashMap<Integer, Integer>();
    Assert.assertEquals(hashMap, cartItems);
  }
}
